name: Run ASoC DAST Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:    # allows manual trigger

jobs:
  asoc-scan:
    runs-on: self-hosted   # your self-hosted runner

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4   # ✅ This pulls your repo code

    - name: Run HCL AppScan on Cloud DAST
      uses: HCL-TECH-SOFTWARE/appscan-scan-action@v1  # ✅ This is the correct Action
      with:
        asoc_key_id: ${{ secrets.ASOC_KEY_ID }}       # Your API Key ID stored in GitHub Secrets
        asoc_key_secret: ${{ secrets.ASOC_KEY_SECRET }} # Your API Secret stored in GitHub Secrets
        scan_name: 'RVPTest'
        scan_type: 'dynamic'
        scan_url: 'https://demo.testfire.net'
        application_id: 'bc39ab99-5c56-4548-b3ed-4f11efc1cba0'
        network: 'public'
        fail_build: false
