name: AppScan DAST Scan

on:
  workflow_dispatch:    # allows manual trigger
  push:
    branches: [ main ]

jobs:
  run-asoc-scan:
    runs-on: self-hosted   # your local runner

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run HCL AppScan on Cloud DAST
      uses: HCL-TECH-SOFTWARE/appscan-scan-action@v1
      with:
        asoc_key_id: ${{ secrets.ASOC_KEY_ID }}
        asoc_key_secret: ${{ secrets.ASOC_KEY_SECRET }}
        scan_name: 'RVPTest'
        scan_type: 'dynamic'
        scan_url: 'https://demo.testfire.net'
